#!/bin/bash
INVENTORY_TAG="@@INVENTORY_TAG@@"
PULSE_AGENT_CONFFILE_FILENAME="@@PULSE_AGENT_CONFFILE_FILENAME@@"
PULSE_SCHEDULER_CONFFILE_FILENAME="@@PULSE_SCHEDULER_CONFFILE_FILENAME@@"
PULSE_INVENTORY_CONFFILE_FILENAME="@@PULSE_INVENTORY_CONFFILE_FILENAME@@"


### Pulse account

echo
echo "#########################"
echo "1. CREATING PULSE ACCOUNT"
echo "#########################"
echo

# Create pulse user
adduser --system --group --home /var/lib/pulse2 --shell /bin/rbash --disabled-password pulse
if ! [ -d "/var/lib/pulse2/.ssh" ]; then
    echo "Create missing SSH profile ..."
    mkdir -p /var/lib/pulse2/.ssh
fi



### SSH Key

echo
echo "############"
echo "2. SETUP SSH"
echo "############"
echo

# Copy SSH keys
chown -R pulse: /var/lib/pulse2
chmod -R 700 /var/lib/pulse2
chmod 600 /var/lib/pulse2/.ssh/authorized_keys

# Open firewall port 22 - TODO
# if shorewall
# echo "ACCEPT net fw tcp 22" >> /etc/shorewall/rules
# service shorewall restart
#
# if ufw
# ufw enable
# sudo ufw allow 5900


### Fusion-Inventory agent

echo
echo "##############################"
echo "3. SETUP FUSIONINVENTORY AGENT"
echo "##############################"
echo

# Setup FusionInventory
FUSION_DIR="/etc/fusioninventory"
FUSION_CFG="${FUSION_DIR}/agent.cfg"

if [ -f ${FUSION_CFG} ];then
    sed -i '/^server/d' ${FUSION_CFG}
    echo "tag = ${INVENTORY_TAG}" > ${FUSION_DIR}/conf.d/tag.cfg 
else
    echo "ERROR: Unable to find fusioninventory config file"
    exit 1
fi



### Setup VNC server

echo
echo "###################"
echo "4. SETUP VNC SERVER"
echo "###################"
echo

# Open firewall port 5900 - TODO
# if shorewall
# echo "ACCEPT net fw tcp 5900" >> /etc/shorewall/rules
# service shorewall restart
#
# if ufw
# ufw enable
# sudo ufw allow 5900


### Pulse agent and plugins

echo
echo "##############"
echo "5. PULSE AGENT"
echo "##############"
echo

# Copy config files
for CONFIG_FILE in $PULSE_AGENT_CONFFILE_FILENAME $PULSE_SCHEDULER_CONFFILE_FILENAME $PULSE_INVENTORY_CONFFILE_FILENAME; do
    if [[ ! -e /etc/pulse-xmpp-agent/${CONFIG_FILE} ]]; then
        cp "${CONFIG_FILE}" /etc/pulse-xmpp-agent/
    fi
done
