#!/bin/bash

# Delay startup until vnc and ssh daemons have started
sleep 60

# Start the agent
export PYCURL_SSL_LIBRARY=openssl
python2 /Library/Python/2.7/site-packages/pulse_xmpp_agent/launcher.py -t machine
